### ISSUE TITLE
having problem with testbench test_top.v

### ISSUE THREAD

**Issue by choi-geunseok** [jasonlo0509/Lenet_Accelerator#3]
Hello. i have a problem with test_top.v

i get the wrong answer when simulating it 

but i get the right answer when simulating test_conv.v, test_fc.v

is there any problem when you doing it?

(by the way i only use G07 folder)

**Comment by jasonlo0509** [comment]
Hi, 
I think you could try test_top_multiple.v, which is final version

We were facing final deadline so there might be some mistakes

thanks
Yun-Chen

**Comment by choi-geunseok** [comment]
Thanks for your answer.

i forgot to tell you that i also ran test_top_multiple.v

it also have the wrong answer

do you have any idea, cause of error?

**Comment by jasonlo0509** [comment]
Hi,

I think we have verified using tool in our school's server at that time. Currently I do not have tool access to verify. Could you help fix it, maybe it is related to newer version of tool.

No, we just focus on multiply and activation and truncation, which is the most time-consuming part.

**Comment by choi-geunseok** [comment]
Thanks for your answer.

When i can fix it, i will tell you.

Have a nice day ^^
